### ISSUE TITLE
Auto load musics list

### ISSUE THREAD

**Issue by mohammadrezaprw** [benkaiser/node-music-player#68]
It seems all musics load on start

**Comment by ohnx** [comment]
Is this not supposed to happen?

**Comment by mohammadrezaprw** [comment]
I have more than 90000 musics and it's not ideal

**Comment by ohnx** [comment]
Ah, so you want an option to turn off automatic music loading?

**Comment by mohammadrezaprw** [comment]
It's better load a numbers of songs on start and then load others on scroll.

**Comment by benkaiser** [comment]
@ohnx Love your first reply. Gold!

@mohammadrezaprw :
First of all, dude, you have a massive library. That's just of the chain.
Currently we send a message of all the songs on load. One optimisation I would like to consider is caching that song info locally in localstorage, and somehow using checksums or something to work out if we need to resend on page load. However with some initial tests on the feasibility of this, my 7233 song library hits 300KB of data, and with a localStorage limit of 5MB (without extending it), 90000 songs at on average the same attribute length would be 3.73MB almost hitting the limit.

We could send them in chunks when the page first loads, but because this is trying to be a music player experience that could rival desktop apps, I feel slow loading from a server when scrolling and whatnot would make it feel clunky, so I would always like to be sending all the data on page load.

If you want to submit a PR for sending the songs down in 1000 song chunks or so I'd be happy to look at that.
